### Site info:
title: Tu Android
tagline: Blog de Android
title: "Blog Tu Android"
description: "Blog dedicado a informar sobre las últimas novedades del mundo Android y a los mejores Smartphones"
keywords: "android, smartphone, móviles"

url: "http://tuandroid.es" # the base hostname & protocol for your site

locales:
    en:
     
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Más categorías"
      Copyright_Notice: "Copyright Notice"
      Resent_Posts: "Últimos artículos"
      
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "





default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)




### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: musicap3
      href: http://musicap3.com
      title: Analisis de productos y accesorios MP3

 # Scripts

analytics :
  provider : google 
  google : 
      tracking_id : ''


### Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/
paginate: 5


exclude: ['README.md', 'LICENSE']
